apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edgerouter
  namespace: prometheus
  labels:
    app: prometheus-operator-edgerouter
    release: prometheus
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: edgerouter
